### ISSUE TITLE
TextureEventObjectをEventに対応させる

### ISSUE THREAD

**Issue by mori08** [mori08/KokoHatena#57]
# objectイベント
- [x] 作成
```toml
[[Event]]
  event = "object"
  type = "texture"
  name = "..." # オブジェクト名
  [Event.param]
    objectKey = "..." # Config.toml に設定されたSliceTexture
    pos = { x=00, y=00 } # 初期座標
```

# actイベント
paramの項目は必須ではない（なければ更新）
- [x] 更新
```toml
[[Event]]
  event = "act"
  name = "..." # オブジェクトを指定
  [Event.param]
    anim = "..." # Config.toml に設定されたAnimation名
    pos = "..." # 移動先の座標
    move = "..." # 座標の移動量
    hide = true # true なら画像を非表示
    mirror = true # true なら画像を反転
```
