### ISSUE TITLE
EventPlayerでjampFlagMapの入出力を行う

### ISSUE THREAD

**Issue by mori08** [mori08/KokoHatena#58]
- [x] m_jampFlagMap に RecordMap のフラグを入力
- [x] m_jampFlagMap から RecordMap へフラグの出力
- [x] flagイベント
```toml
[[Event]]
  event = "flag"
  name = "..." # flag名
  value = true # デフォルトはtrue
```
