### ISSUE TITLE
TextEventObjectの作成

### ISSUE THREAD

**Issue by mori08** [mori08/KokoHatena#59]
# Objectイベント
- [x] 作成
```toml
[[Event]]
  event = "object"
  type = "message"
  name = "ui_text"
    [Event.param]
```

# Actイベント
- [x] 更新
```toml
[[Event]]
  event = "act"
  name = "ui_text"
  [Event.param]
    type = "..." # "message" or "select"

    # message の場合
    text = "..." # 本文
    speaker = true # true の場合 プレイヤー

    # select の場合
    select  = [
        {text="選択肢1", flag="フラグ名1"},
        {text="選択肢2", flag="フラグ名2"},
        # 3つ以上指定可能
    ]
```
