### ISSUE TITLE
MessageBoardからEventPlayerに受け取ったrequestTextを送る

### ISSUE THREAD

**Issue by mori08** [mori08/KokoHatena#73]
- [ ] EventPlayerでrequestを待つ状態の作成
- [ ] EventPlayerでrequestを受け取る処理の作成

```toml
[[Event]]
  event = "receive"
  name = "..." # requestTextで指定する文字列
```
