### ISSUE TITLE
EventPlayerの指定された時間待機するイベントを作成

### ISSUE THREAD

**Issue by mori08** [mori08/KokoHatena#80]
指定された秒数の間イベントを進ませない

```toml
[[Event]]
  event = "wait"
  time = 1.0
```
